# Generated by Django 5.2.4 on 2025-07-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
