# Generated by Django 5.2.4 on 2025-08-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_delete_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('landmark', models.CharField(blank=True, max_length=100)),
                ('delivery_method', models.CharField(choices=[('pickup', 'استلام من الفرع'), ('delivery', 'توصيل للمنزل')], max_length=10)),
                ('items', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
